### ISSUE TITLE
 Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by tuannguyenminh2086** [timwis/vue-lil-context-menu#3]
Hi,
I installed your component and it have a issue:
"Uncaught TypeError: Cannot read property 'open' of undefined  at contextmenu "

**Comment by timwis** [comment]
Hi, can you paste your code? My guess is you didn't add a `ref` to your context menu (see sample in readme)

**Comment by tuannguyenminh2086** [comment]
Hi,
I got to fixed the problem. I installed this package is not support for vuejs 2. So I found one and that fixed

**Comment by timwis** [comment]
This package does indeed support Vue 2. It was written for it.
