### ISSUE TITLE
Bug on firefox

### ISSUE THREAD

**Issue by cukikt0302** [timwis/vue-lil-context-menu#4]
firefox Wrong pisition in this image
![screenshot 3](https://user-images.githubusercontent.com/26678541/27760855-8f9b2a60-5e7b-11e7-90a2-392eab5ee1ed.png)

**Comment by timwis** [comment]
All sorted? (App looks cool by the way!)

**Comment by cukikt0302** [comment]
Oops sorry
Im wrong project
resolved https://github.com/vmaimone/vue-context-menu ^_^
It's just adminlte :)
